# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0006_auto_20160519_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawtransaction',
            name='state',
            field=models.CharField(choices=[('NEW', 'New'), ('ERROR', 'Error'), ('DONE', 'Done')], default='DONE', max_length=10, verbose_name='Txid'),
        ),
    ]
