# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0009_WT_ixid_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawtransaction',
            name='walletconflicts',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Walletconflicts txid'),
        ),
    ]
